### ISSUE TITLE
Show property values in the device element and add a divisor for integer encoded floating point values

### ISSUE THREAD

**Issue by amirgol** [tim-hellhake/modbus-adapter#3]
Hi,
How can I add devices to the main dashboard? I used Modbus simulator ion my PC and my Raspberry pi connect to my PC and read data. but How can I show the value or add a device on the "things" dashboard?

**Comment by tim-hellhake** [comment]
Hi @amirgol,

after configuring a Modbus device in the settings of the adapter you should be able to see in the `Add new things` dialog.
Did you check the logs for errors?
You find them at `http://[your gateway]/settings/developer`.

**Comment by amirgol** [comment]
Hi @tim-hellhake,
Thank you. I found It.
The problem is now the parameter value. It does no show the register value on the main page. and I must open the device to see the parameters. You can see in the below screenshot, RAM and System show value but on the right, Voltage (from Modbus) does not show the value.
![Capture](https://user-images.githubusercontent.com/6647326/98459576-745b4a80-21b1-11eb-8552-438142fc3782.PNG)
How can assign one parameter as a main and show it on the things page?
Also, my parameter must be divided into 100. How can I do that? for example, the Modbus value is 314, but the real value is 3.14. How can I show real value?

**Comment by tim-hellhake** [comment]
> It does no show the register value on the main page

The way this works is the adapter provides a type for the device and the property.
Based on this information, the gateway then decides how to render the device.
You can see all available types [here](https://iot.mozilla.org/schemas/).
Let's say you have a smart meter and want to see the current power instead of `THING`.
You would have to set the device type to `SmartPlug` and the property type to `InstantaneousPowerProperty`.
At the moment, there is no way to set the type in the config, but I will add it in the next update.

> Also, my parameter must be divided into 100. How can I do that?

That's currently not possible.
I'll add a config option for it.

**Comment by tim-hellhake** [comment]
> It does no show the register value on the main page

This works for the systeminfo-adapter because the adapter provides a capability for the device and a type for the property.
Based on this information, the gateway then decides how to render the device.
You can see all available capabilities [here](https://iot.mozilla.org/schemas/).
Let's say you have a temperature sensor and want to see the current temperature instead of `THING`.
You would have to add the capability `TemperatureSensor` to the device and set the property type to `TemperatureSensor`.
If you don't find a matching capability/type you can always use `MultiLevelSensor` for the device and `LevelProperty` for the property.
As you can see [here](https://iot.mozilla.org/schemas/#LevelProperty) the `LevelProperty` always needs a `minimum`/`maximum`.
At the moment, there is no way to set those values in the config, but I will add it in the next update.

> Also, my parameter must be divided into 100. How can I do that?

That's currently not possible.
I'll add a config option for it.

**Comment by tim-hellhake** [comment]
As soon as the linked PR is merged you can test the new update.

**Comment by amirgol** [comment]
Thank you for the fast releasing update.

**Comment by tim-hellhake** [comment]
Can we close the issue or did you experience any problems?

**Comment by amirgol** [comment]
Yes of course. thanks
